# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'YOUTUBE_FormMain.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QScrollArea, QSizePolicy, QSpacerItem,
    QSplitter, QStatusBar, QTextEdit, QToolBar,
    QVBoxLayout, QWidget)
import YOUTUBE_images_rc

class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        if not FormMainWindow.objectName():
            FormMainWindow.setObjectName(u"FormMainWindow")
        FormMainWindow.resize(800, 600)
        FormMainWindow.setMinimumSize(QSize(800, 600))
        FormMainWindow.setMaximumSize(QSize(800, 600))
        FormMainWindow.setInputMethodHints(Qt.ImhNone)
        self.action_CreateYoutube = QAction(FormMainWindow)
        self.action_CreateYoutube.setObjectName(u"action_CreateYoutube")
        self.action_CreateYoutube.setCheckable(True)
        self.action_CreateYoutube.setChecked(True)
        icon = QIcon()
        icon.addFile(u":/ICONS/add-link-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/ICONS/add-link-xl.png", QSize(), QIcon.Normal, QIcon.On)
        self.action_CreateYoutube.setIcon(icon)
        self.action_Exit = QAction(FormMainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        self.action_Exit.setCheckable(True)
        icon1 = QIcon()
        icon1.addFile(u":/ICONS/exit-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/ICONS/exit-xl.png", QSize(), QIcon.Normal, QIcon.On)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setProperty("clicked()", False)
        self.action_Action_Cut = QAction(FormMainWindow)
        self.action_Action_Cut.setObjectName(u"action_Action_Cut")
        icon2 = QIcon()
        icon2.addFile(u":/ICONS/cut-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Action_Cut.setIcon(icon2)
        self.action_Action_Copy = QAction(FormMainWindow)
        self.action_Action_Copy.setObjectName(u"action_Action_Copy")
        icon3 = QIcon()
        icon3.addFile(u":/ICONS/copy-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Action_Copy.setIcon(icon3)
        self.action_Action_Paste = QAction(FormMainWindow)
        self.action_Action_Paste.setObjectName(u"action_Action_Paste")
        self.action_Setup = QAction(FormMainWindow)
        self.action_Setup.setObjectName(u"action_Setup")
        icon4 = QIcon()
        iconThemeName = u"applications-engineering"
        if QIcon.hasThemeIcon(iconThemeName):
            icon4 = QIcon.fromTheme(iconThemeName)
        else:
            icon4.addFile(u":/ICONS/settings-5-xl.png", QSize(), QIcon.Normal, QIcon.On)

        self.action_Setup.setIcon(icon4)
        self.action_Setup.setVisible(True)
        self.centralwidget = QWidget(FormMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 0, 2, 2))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMaximumSize(QSize(1000, 1505))
        self.splitter_2.setOrientation(Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter = QSplitter(self.splitter_2)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setMaximumSize(QSize(16777215, 500))
        self.splitter.setOrientation(Qt.Horizontal)
        self.ListViewL = QListView(self.splitter)
        self.ListViewL.setObjectName(u"ListViewL")
        sizePolicy.setHeightForWidth(self.ListViewL.sizePolicy().hasHeightForWidth())
        self.ListViewL.setSizePolicy(sizePolicy)
        self.ListViewL.setMinimumSize(QSize(0, 0))
        self.ListViewL.setMaximumSize(QSize(300, 500))
        self.ListViewL.setSizeIncrement(QSize(0, 0))
        self.splitter.addWidget(self.ListViewL)
        self.FrameR = QFrame(self.splitter)
        self.FrameR.setObjectName(u"FrameR")
        self.FrameR.setFrameShape(QFrame.StyledPanel)
        self.FrameR.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.FrameR)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.ScrollAreaR = QScrollArea(self.FrameR)
        self.ScrollAreaR.setObjectName(u"ScrollAreaR")
        self.ScrollAreaR.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.ScrollAreaR.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.ScrollAreaR.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 438, 368))
        self.verticalLayout_3 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.TextEditR = QTextEdit(self.scrollAreaWidgetContents)
        self.TextEditR.setObjectName(u"TextEditR")
        self.TextEditR.setEnabled(False)
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.TextEditR.sizePolicy().hasHeightForWidth())
        self.TextEditR.setSizePolicy(sizePolicy1)
        self.TextEditR.setMinimumSize(QSize(0, 0))
        self.TextEditR.setMaximumSize(QSize(500, 900))

        self.verticalLayout_3.addWidget(self.TextEditR)

        self.VerticalSpacerR = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_3.addItem(self.VerticalSpacerR)

        self.ScrollAreaR.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout.addWidget(self.ScrollAreaR)

        self.splitter.addWidget(self.FrameR)
        self.splitter_2.addWidget(self.splitter)
        self.Memo_Log = QPlainTextEdit(self.splitter_2)
        self.Memo_Log.setObjectName(u"Memo_Log")
        sizePolicy.setHeightForWidth(self.Memo_Log.sizePolicy().hasHeightForWidth())
        self.Memo_Log.setSizePolicy(sizePolicy)
        self.Memo_Log.setMinimumSize(QSize(0, 0))
        self.Memo_Log.setMaximumSize(QSize(1000, 1000))
        font = QFont()
        font.setFamilies([u"Courier New"])
        font.setPointSize(8)
        font.setBold(True)
        self.Memo_Log.setFont(font)
        self.Memo_Log.setAutoFillBackground(True)
        self.Memo_Log.setStyleSheet(u"")
        self.Memo_Log.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhSensitiveData)
        self.Memo_Log.setFrameShape(QFrame.StyledPanel)
        self.Memo_Log.setFrameShadow(QFrame.Plain)
        self.Memo_Log.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.Memo_Log.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.Memo_Log.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.Memo_Log.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.Memo_Log.setReadOnly(True)
        self.Memo_Log.setBackgroundVisible(False)
        self.splitter_2.addWidget(self.Memo_Log)

        self.verticalLayout_2.addWidget(self.splitter_2)

        FormMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FormMainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        icon5 = QIcon()
        icon5.addFile(u":/ICONS/info-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_Help.setIcon(icon5)
        FormMainWindow.setMenuBar(self.menubar)
        self.StatusBar_P1_P2 = QStatusBar(FormMainWindow)
        self.StatusBar_P1_P2.setObjectName(u"StatusBar_P1_P2")
        FormMainWindow.setStatusBar(self.StatusBar_P1_P2)
        self.toolBar = QToolBar(FormMainWindow)
        self.toolBar.setObjectName(u"toolBar")
        FormMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.ListViewL, self.Memo_Log)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.action_CreateYoutube)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_Action_Cut)
        self.menu_Edit.addAction(self.action_Action_Copy)
        self.menu_Edit.addAction(self.action_Action_Paste)
        self.menu_Edit.addSeparator()
        self.menu.addAction(self.action_Setup)
        self.menu.addSeparator()
        self.menu_Help.addSeparator()
        self.toolBar.addAction(self.action_Exit)
        self.toolBar.addAction(self.action_CreateYoutube)
        self.toolBar.addAction(self.action_Setup)

        self.retranslateUi(FormMainWindow)
        self.action_Exit.triggered.connect(FormMainWindow.close)

        QMetaObject.connectSlotsByName(FormMainWindow)
    # setupUi

    def retranslateUi(self, FormMainWindow):
        FormMainWindow.setWindowTitle(QCoreApplication.translate("FormMainWindow", u"FormMainWindow", None))
        self.action_CreateYoutube.setText(QCoreApplication.translate("FormMainWindow", u"\u0421\u043e\u0437\u0434\u0430\u0442\u044c Youtube", None))
#if QT_CONFIG(tooltip)
        self.action_CreateYoutube.setToolTip(QCoreApplication.translate("FormMainWindow", u"\u0421\u043e\u0437\u0434\u0430\u0442\u044c Youtube", None))
#endif // QT_CONFIG(tooltip)
        self.action_Exit.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        self.action_Action_Cut.setText(QCoreApplication.translate("FormMainWindow", u"Action_Cut", None))
        self.action_Action_Copy.setText(QCoreApplication.translate("FormMainWindow", u"Action_Copy", None))
        self.action_Action_Paste.setText(QCoreApplication.translate("FormMainWindow", u"Action_Paste", None))
        self.action_Setup.setText(QCoreApplication.translate("FormMainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430", None))
        self.menu_File.setTitle(QCoreApplication.translate("FormMainWindow", u"File", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("FormMainWindow", u"Edit", None))
        self.menu.setTitle(QCoreApplication.translate("FormMainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430", None))
        self.menu_Help.setTitle(QCoreApplication.translate("FormMainWindow", u"\u0421\u043f\u0440\u0430\u0432\u043a\u0430 \u043f\u043e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("FormMainWindow", u"toolBar", None))
    # retranslateUi

