# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'YOUTUBE_FormMain.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QProgressBar, QScrollArea, QSizePolicy,
    QSpacerItem, QSplitter, QStatusBar, QTextEdit,
    QToolBar, QVBoxLayout, QWidget)
import YOUTUBE_images_rc

class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        if not FormMainWindow.objectName():
            FormMainWindow.setObjectName(u"FormMainWindow")
        FormMainWindow.resize(800, 600)
        FormMainWindow.setMinimumSize(QSize(800, 600))
        FormMainWindow.setMaximumSize(QSize(16777215, 16777215))
        FormMainWindow.setInputMethodHints(Qt.ImhNone)
        self.action_CreateYoutube = QAction(FormMainWindow)
        self.action_CreateYoutube.setObjectName(u"action_CreateYoutube")
        self.action_CreateYoutube.setChecked(False)
        icon = QIcon()
        icon.addFile(u":/ICONS/add-image-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_CreateYoutube.setIcon(icon)
        self.action_Exit = QAction(FormMainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        icon1 = QIcon()
        icon1.addFile(u":/ICONS/exit-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/ICONS/exit-xl.png", QSize(), QIcon.Normal, QIcon.On)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setProperty("clicked()", False)
        self.action_Cut = QAction(FormMainWindow)
        self.action_Cut.setObjectName(u"action_Cut")
        icon2 = QIcon()
        icon2.addFile(u":/ICONS/cut-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Cut.setIcon(icon2)
        self.action_Copy = QAction(FormMainWindow)
        self.action_Copy.setObjectName(u"action_Copy")
        icon3 = QIcon()
        icon3.addFile(u":/ICONS/copy-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Copy.setIcon(icon3)
        self.action_Paste = QAction(FormMainWindow)
        self.action_Paste.setObjectName(u"action_Paste")
        self.action_Setup = QAction(FormMainWindow)
        self.action_Setup.setObjectName(u"action_Setup")
        icon4 = QIcon()
        icon4.addFile(u":/ICONS/icons8-\u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u0435-48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Setup.setIcon(icon4)
        self.action_Setup.setVisible(True)
        self.action_DeleteAll = QAction(FormMainWindow)
        self.action_DeleteAll.setObjectName(u"action_DeleteAll")
        self.action_Start_Stop = QAction(FormMainWindow)
        self.action_Start_Stop.setObjectName(u"action_Start_Stop")
        icon5 = QIcon()
        icon5.addFile(u":/ICONS/run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Start_Stop.setIcon(icon5)
        self.action_About = QAction(FormMainWindow)
        self.action_About.setObjectName(u"action_About")
        self.action_Help = QAction(FormMainWindow)
        self.action_Help.setObjectName(u"action_Help")
        icon6 = QIcon()
        icon6.addFile(u":/ICONS/help-xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Help.setIcon(icon6)
        self.action_ExitProgram = QAction(FormMainWindow)
        self.action_ExitProgram.setObjectName(u"action_ExitProgram")
        self.action_ExitProgram.setCheckable(True)
        self.action_TestFunction = QAction(FormMainWindow)
        self.action_TestFunction.setObjectName(u"action_TestFunction")
        icon7 = QIcon()
        icon7.addFile(u":/ICONS/sign_out_32px.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_TestFunction.setIcon(icon7)
        self.centralwidget = QWidget(FormMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 0, 2, 2))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMaximumSize(QSize(16777215, 16777215))
        self.splitter_2.setOrientation(Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter = QSplitter(self.splitter_2)
        self.splitter.setObjectName(u"splitter")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy1)
        self.splitter.setMaximumSize(QSize(16777215, 16777215))
        self.splitter.setOrientation(Qt.Horizontal)
        self.ListViewL = QListView(self.splitter)
        self.ListViewL.setObjectName(u"ListViewL")
        sizePolicy.setHeightForWidth(self.ListViewL.sizePolicy().hasHeightForWidth())
        self.ListViewL.setSizePolicy(sizePolicy)
        self.ListViewL.setMinimumSize(QSize(300, 300))
        self.ListViewL.setMaximumSize(QSize(300, 16777215))
        self.ListViewL.setSizeIncrement(QSize(0, 0))
        self.splitter.addWidget(self.ListViewL)
        self.FrameR = QFrame(self.splitter)
        self.FrameR.setObjectName(u"FrameR")
        sizePolicy1.setHeightForWidth(self.FrameR.sizePolicy().hasHeightForWidth())
        self.FrameR.setSizePolicy(sizePolicy1)
        self.FrameR.setFrameShape(QFrame.StyledPanel)
        self.FrameR.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.FrameR)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.ScrollAreaR = QScrollArea(self.FrameR)
        self.ScrollAreaR.setObjectName(u"ScrollAreaR")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.ScrollAreaR.sizePolicy().hasHeightForWidth())
        self.ScrollAreaR.setSizePolicy(sizePolicy2)
        self.ScrollAreaR.setMinimumSize(QSize(0, 0))
        self.ScrollAreaR.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ScrollAreaR.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ScrollAreaR.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 454, 870))
        sizePolicy1.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy1)
        self.verticalLayout_3 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.TEST_widget = QWidget(self.scrollAreaWidgetContents)
        self.TEST_widget.setObjectName(u"TEST_widget")
        self.TEST_widget.setMinimumSize(QSize(0, 40))
        self.TEST_widget.setMaximumSize(QSize(16777203, 40))
        font = QFont()
        font.setPointSize(10)
        self.TEST_widget.setFont(font)
        self.TEST_widget.setStyleSheet(u"background-color: rgb(0, 0, 255);")
        self.verticalLayout_4 = QVBoxLayout(self.TEST_widget)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.progressBar = QProgressBar(self.TEST_widget)
        self.progressBar.setObjectName(u"progressBar")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy3)
        self.progressBar.setMinimumSize(QSize(0, 15))
        self.progressBar.setValue(24)
        self.progressBar.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.progressBar.setOrientation(Qt.Horizontal)

        self.verticalLayout_4.addWidget(self.progressBar)


        self.verticalLayout_3.addWidget(self.TEST_widget)

        self.TextEditR = QTextEdit(self.scrollAreaWidgetContents)
        self.TextEditR.setObjectName(u"TextEditR")
        self.TextEditR.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.TextEditR.sizePolicy().hasHeightForWidth())
        self.TextEditR.setSizePolicy(sizePolicy1)
        self.TextEditR.setMinimumSize(QSize(0, 800))
        self.TextEditR.setMaximumSize(QSize(16777215, 16777215))
        self.TextEditR.setSizeIncrement(QSize(0, -1))
        font1 = QFont()
        font1.setFamilies([u"Courier New"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.TextEditR.setFont(font1)
        self.TextEditR.setStyleSheet(u"background-color: rgb(152, 152, 152);")
        self.TextEditR.setFrameShape(QFrame.NoFrame)
        self.TextEditR.setFrameShadow(QFrame.Plain)
        self.TextEditR.setLineWidth(6)
        self.TextEditR.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.TextEditR.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.TextEditR.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.TextEditR.setReadOnly(True)

        self.verticalLayout_3.addWidget(self.TextEditR)

        self.VerticalSpacerR = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_3.addItem(self.VerticalSpacerR)

        self.ScrollAreaR.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout.addWidget(self.ScrollAreaR)

        self.splitter.addWidget(self.FrameR)
        self.splitter_2.addWidget(self.splitter)
        self.Memo_Log = QPlainTextEdit(self.splitter_2)
        self.Memo_Log.setObjectName(u"Memo_Log")
        sizePolicy.setHeightForWidth(self.Memo_Log.sizePolicy().hasHeightForWidth())
        self.Memo_Log.setSizePolicy(sizePolicy)
        self.Memo_Log.setMinimumSize(QSize(300, 150))
        self.Memo_Log.setMaximumSize(QSize(16777215, 16777215))
        font2 = QFont()
        font2.setFamilies([u"Courier New"])
        font2.setPointSize(8)
        font2.setBold(True)
        self.Memo_Log.setFont(font2)
        self.Memo_Log.setAutoFillBackground(True)
        self.Memo_Log.setStyleSheet(u"")
        self.Memo_Log.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhSensitiveData)
        self.Memo_Log.setFrameShape(QFrame.StyledPanel)
        self.Memo_Log.setFrameShadow(QFrame.Plain)
        self.Memo_Log.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Memo_Log.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Memo_Log.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.Memo_Log.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.Memo_Log.setReadOnly(True)
        self.Memo_Log.setBackgroundVisible(False)
        self.splitter_2.addWidget(self.Memo_Log)

        self.verticalLayout_2.addWidget(self.splitter_2)

        FormMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FormMainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        FormMainWindow.setMenuBar(self.menubar)
        self.StatusBar_PN = QStatusBar(FormMainWindow)
        self.StatusBar_PN.setObjectName(u"StatusBar_PN")
        self.StatusBar_PN.setFont(font)
        FormMainWindow.setStatusBar(self.StatusBar_PN)
        self.toolBar = QToolBar(FormMainWindow)
        self.toolBar.setObjectName(u"toolBar")
        FormMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.ListViewL, self.Memo_Log)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.action_CreateYoutube)
        self.menu_File.addAction(self.action_DeleteAll)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menu.addAction(self.action_Setup)
        self.menu.addSeparator()
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.toolBar.addAction(self.action_Exit)
        self.toolBar.addAction(self.action_CreateYoutube)
        self.toolBar.addAction(self.action_DeleteAll)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Start_Stop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Setup)
        self.toolBar.addAction(self.action_About)
        self.toolBar.addAction(self.action_Help)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ExitProgram)
        self.toolBar.addAction(self.action_TestFunction)

        self.retranslateUi(FormMainWindow)
        self.action_ExitProgram.triggered.connect(FormMainWindow.close)

        QMetaObject.connectSlotsByName(FormMainWindow)
    # setupUi

    def retranslateUi(self, FormMainWindow):
        FormMainWindow.setWindowTitle(QCoreApplication.translate("FormMainWindow", u"FormMainWindow", None))
        self.action_CreateYoutube.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0441\u0441\u044b\u043b\u043a\u0443", None))
#if QT_CONFIG(tooltip)
        self.action_CreateYoutube.setToolTip(QCoreApplication.translate("FormMainWindow", u"\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0441\u0441\u044b\u043b\u043a\u0443", None))
#endif // QT_CONFIG(tooltip)
        self.action_Exit.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        self.action_Cut.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u044b\u0440\u0435\u0437\u0430\u0442\u044c", None))
        self.action_Copy.setText(QCoreApplication.translate("FormMainWindow", u"\u041a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c", None))
        self.action_Paste.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c", None))
        self.action_Setup.setText(QCoreApplication.translate("FormMainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430", None))
        self.action_DeleteAll.setText(QCoreApplication.translate("FormMainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435 \u0441\u0441\u044b\u043b\u043a\u0438", None))
        self.action_Start_Stop.setText(QCoreApplication.translate("FormMainWindow", u"\u0421\u0442\u0430\u0440\u0442_\u0421\u0442\u043e\u043f", None))
        self.action_Start_Stop.setIconText(QCoreApplication.translate("FormMainWindow", u"\u0421\u0442\u0430\u0440\u0442_\u0421\u0442\u043e\u043f", None))
#if QT_CONFIG(tooltip)
        self.action_Start_Stop.setToolTip(QCoreApplication.translate("FormMainWindow", u"\u0421\u0442\u0430\u0440\u0442_\u0421\u0442\u043e\u043f", None))
#endif // QT_CONFIG(tooltip)
        self.action_About.setText(QCoreApplication.translate("FormMainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.action_Help.setText(QCoreApplication.translate("FormMainWindow", u"\u041f\u043e\u043c\u043e\u0449\u044c", None))
        self.action_ExitProgram.setText(QCoreApplication.translate("FormMainWindow", u"\u0412\u044b\u0445\u043e\u0434 \u0438\u0437 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b", None))
        self.action_TestFunction.setText(QCoreApplication.translate("FormMainWindow", u"TestFunction", None))
#if QT_CONFIG(tooltip)
        self.action_TestFunction.setToolTip(QCoreApplication.translate("FormMainWindow", u"\u0422\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0444\u0443\u043d\u043a\u0446\u0438\u0439", None))
#endif // QT_CONFIG(tooltip)
        self.menu_File.setTitle(QCoreApplication.translate("FormMainWindow", u"File", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("FormMainWindow", u"Edit", None))
        self.menu.setTitle(QCoreApplication.translate("FormMainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430", None))
        self.menu_Help.setTitle(QCoreApplication.translate("FormMainWindow", u"\u0421\u043f\u0440\u0430\u0432\u043a\u0430 \u043f\u043e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("FormMainWindow", u"toolBar", None))
    # retranslateUi

