# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'YOUTUBE_About.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QGraphicsView, QLabel, QSizePolicy, QWidget)

class Ui_FormAbout(object):
    def setupUi(self, FormAbout):
        if not FormAbout.objectName():
            FormAbout.setObjectName(u"FormAbout")
        FormAbout.resize(400, 300)
        FormAbout.setModal(True)
        self.buttonBox_OK = QDialogButtonBox(FormAbout)
        self.buttonBox_OK.setObjectName(u"buttonBox_OK")
        self.buttonBox_OK.setGeometry(QRect(30, 260, 341, 32))
        self.buttonBox_OK.setOrientation(Qt.Horizontal)
        self.buttonBox_OK.setStandardButtons(QDialogButtonBox.Ok)
        self.buttonBox_OK.setCenterButtons(True)
        self.graphics_ICON = QGraphicsView(FormAbout)
        self.graphics_ICON.setObjectName(u"graphics_ICON")
        self.graphics_ICON.setGeometry(QRect(10, 10, 110, 110))
        self.graphics_ICON.setMinimumSize(QSize(110, 110))
        self.graphics_ICON.setMaximumSize(QSize(110, 110))
        self.label_APP = QLabel(FormAbout)
        self.label_APP.setObjectName(u"label_APP")
        self.label_APP.setGeometry(QRect(140, 10, 200, 110))
        self.label_APP.setMinimumSize(QSize(200, 110))
        self.label_APP.setMaximumSize(QSize(110, 110))
        font = QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_APP.setFont(font)
        self.label_APP_2 = QLabel(FormAbout)
        self.label_APP_2.setObjectName(u"label_APP_2")
        self.label_APP_2.setGeometry(QRect(10, 130, 381, 25))
        self.label_APP_2.setMinimumSize(QSize(300, 25))
        self.label_APP_2.setMaximumSize(QSize(400, 25))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.label_APP_2.setFont(font1)
        self.label_APP_3 = QLabel(FormAbout)
        self.label_APP_3.setObjectName(u"label_APP_3")
        self.label_APP_3.setGeometry(QRect(10, 160, 100, 15))
        self.label_APP_3.setMinimumSize(QSize(100, 15))
        self.label_APP_3.setMaximumSize(QSize(400, 15))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(False)
        self.label_APP_3.setFont(font2)
        self.label_APP_4 = QLabel(FormAbout)
        self.label_APP_4.setObjectName(u"label_APP_4")
        self.label_APP_4.setGeometry(QRect(160, 160, 211, 15))
        self.label_APP_4.setMinimumSize(QSize(100, 15))
        self.label_APP_4.setMaximumSize(QSize(400, 15))
        self.label_APP_4.setFont(font2)
        self.label_APP_4.setStyleSheet(u"background-color: rgb(190, 190, 190);")
        self.label_APP_5 = QLabel(FormAbout)
        self.label_APP_5.setObjectName(u"label_APP_5")
        self.label_APP_5.setGeometry(QRect(10, 220, 61, 15))
        self.label_APP_5.setMinimumSize(QSize(50, 15))
        self.label_APP_5.setMaximumSize(QSize(400, 15))
        self.label_APP_5.setFont(font2)
        self.label_APP_6 = QLabel(FormAbout)
        self.label_APP_6.setObjectName(u"label_APP_6")
        self.label_APP_6.setGeometry(QRect(160, 220, 71, 15))
        self.label_APP_6.setMinimumSize(QSize(50, 15))
        self.label_APP_6.setMaximumSize(QSize(400, 15))
        self.label_APP_6.setFont(font2)
        self.label_APP_6.setStyleSheet(u"background-color: rgb(190, 190, 190);")
        self.label_APP_7 = QLabel(FormAbout)
        self.label_APP_7.setObjectName(u"label_APP_7")
        self.label_APP_7.setGeometry(QRect(250, 220, 21, 15))
        self.label_APP_7.setMinimumSize(QSize(10, 15))
        self.label_APP_7.setMaximumSize(QSize(400, 15))
        self.label_APP_7.setFont(font2)
        self.label_APP_8 = QLabel(FormAbout)
        self.label_APP_8.setObjectName(u"label_APP_8")
        self.label_APP_8.setGeometry(QRect(290, 220, 71, 15))
        self.label_APP_8.setMinimumSize(QSize(50, 15))
        self.label_APP_8.setMaximumSize(QSize(400, 15))
        self.label_APP_8.setFont(font2)
        self.label_APP_8.setStyleSheet(u"background-color: rgb(190, 190, 190);")
        self.label_APP_9 = QLabel(FormAbout)
        self.label_APP_9.setObjectName(u"label_APP_9")
        self.label_APP_9.setGeometry(QRect(10, 200, 61, 15))
        self.label_APP_9.setMinimumSize(QSize(50, 15))
        self.label_APP_9.setMaximumSize(QSize(400, 15))
        self.label_APP_9.setFont(font2)
        self.label_APP_10 = QLabel(FormAbout)
        self.label_APP_10.setObjectName(u"label_APP_10")
        self.label_APP_10.setGeometry(QRect(90, 200, 281, 15))
        self.label_APP_10.setMinimumSize(QSize(50, 15))
        self.label_APP_10.setMaximumSize(QSize(400, 15))
        self.label_APP_10.setFont(font2)
        self.label_APP_10.setStyleSheet(u"background-color: rgb(190, 190, 190);")
        self.label_APP_11 = QLabel(FormAbout)
        self.label_APP_11.setObjectName(u"label_APP_11")
        self.label_APP_11.setGeometry(QRect(10, 180, 361, 15))
        self.label_APP_11.setMinimumSize(QSize(50, 15))
        self.label_APP_11.setMaximumSize(QSize(400, 15))
        self.label_APP_11.setFont(font2)
        self.label_APP_11.setStyleSheet(u"background-color: rgb(190, 190, 190);")

        self.retranslateUi(FormAbout)
        self.buttonBox_OK.accepted.connect(FormAbout.accept)
        self.buttonBox_OK.rejected.connect(FormAbout.reject)

        QMetaObject.connectSlotsByName(FormAbout)
    # setupUi

    def retranslateUi(self, FormAbout):
        FormAbout.setWindowTitle(QCoreApplication.translate("FormAbout", u"Dialog", None))
        self.label_APP.setText(QCoreApplication.translate("FormAbout", u"YOUTUBE", None))
        self.label_APP_2.setText(QCoreApplication.translate("FormAbout", u"YOUTUBE", None))
        self.label_APP_3.setText(QCoreApplication.translate("FormAbout", u"\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f", None))
        self.label_APP_4.setText(QCoreApplication.translate("FormAbout", u"\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f", None))
        self.label_APP_5.setText(QCoreApplication.translate("FormAbout", u"\u0412\u0435\u0440\u0441\u0438\u044f", None))
        self.label_APP_6.setText(QCoreApplication.translate("FormAbout", u"1.0", None))
        self.label_APP_7.setText(QCoreApplication.translate("FormAbout", u"\u043e\u0442", None))
        self.label_APP_8.setText(QCoreApplication.translate("FormAbout", u"07.06.2023", None))
        self.label_APP_9.setText(QCoreApplication.translate("FormAbout", u"\u0422\u0435\u043b\u0435\u0444\u043e\u043d", None))
        self.label_APP_10.setText(QCoreApplication.translate("FormAbout", u"\u0422\u0435\u043b\u0435\u0444\u043e\u043d", None))
        self.label_APP_11.setText(QCoreApplication.translate("FormAbout", u"\u041b\u0438\u0441\u0438\u0446\u044b\u043d \u042e\u0440\u0438\u0439 \u0420\u043e\u043d\u043e\u0432\u0438\u0447", None))
    # retranslateUi

